### ISSUE TITLE
[bug] Tooltip content wrap

### ISSUE THREAD

**Issue by Tnifey** [aurolia-css/aurolia-css.github.io#2]
Tooltips often have one line (two or more lines are not too common). In your tooltip when content have more than one word, it makes line break between words. You can use `white-space: pre;` to prevent that. 
In more than one liners use `&#xa;` (or actual break-line by pressing [enter]) ([ad1]) as break-line (according to [this stackoverflow answer](https://stackoverflow.com/a/16452853).

[ad1]
![image](https://user-images.githubusercontent.com/8442019/65820957-a6208480-e22f-11e9-8243-02d3dfc4530f.png)

```css
[data-tooltip]:before {
  white-space: pre;
}
```

before:
![image](https://user-images.githubusercontent.com/8442019/65820751-22fe2f00-e22d-11e9-87eb-715426571f72.png)

after:
![image](https://user-images.githubusercontent.com/8442019/65820778-6789ca80-e22d-11e9-9a77-5f73e6f0163e.png)

after with line-break `&#xa;` and with actual line break ([ad1]):
![image](https://user-images.githubusercontent.com/8442019/65820897-dae00c00-e22e-11e9-941e-6ccf0812d724.png)

**Comment by IgorKowalczyk** [comment]
Oh I forgot about it, fixed and the documentation fixed. Thank you.

[Try Fixed Demo](https://aurolia-css.github.io/tooltip)
